/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pack3DJNI */

#ifndef _Included_Pack3DJNI
#define _Included_Pack3DJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pack3DJNI
 * Method:    getCount
 * Signature: (FFFFFF)I
 */
JNIEXPORT jint JNICALL Java_Pack3DJNI_getCount
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
